/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "brand-dark": "#DC0016",
        "tertiary-fixed-dim": "#adc6ff",
        "outline-variant": "#e6bdb8",
        "background": "#f9f9f9",
        "tertiary-fixed": "#d8e2ff",
        "info": "#3B82F6",
        "surface-container-lowest": "#ffffff",
        "surface": "#f9f9f9",
        "surface-container-high": "#e8e8e8",
        "tertiary": "#003f8c",
        "brand-subtle": "#FEE2E2",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-dim": "#dadada",
        "secondary-container": "#dbe2f8",
        "on-surface": "#1a1c1c",
        "on-primary-fixed-variant": "#93000b",
        "on-error": "#ffffff",
        "on-tertiary-container": "#bed1ff",
        "success": "#10B981",
        "on-tertiary-fixed": "#001a41",
        "primary-fixed-dim": "#ffb4ab",
        "secondary": "#575e70",
        "inverse-surface": "#2f3131",
        "on-primary-container": "#ffffff",
        "surface-tint": "#DC0016",
        "inverse-primary": "#ffb4ab",
        "surface-variant": "#e2e2e2",
        "error-container": "#ffdad6",
        "warning": "#F59E0B",
        "on-primary-fixed": "#410002",
        "primary-fixed": "#ffdad6",
        "error": "#EF4444",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#bfc6db",
        "primary": "#DC0016",
        "tertiary-container": "#0056b9",
        "on-secondary-container": "#5d6476",
        "surface-container-highest": "#e2e2e2",
        "outline": "#916f6b",
        "surface-bright": "#f9f9f9",
        "secondary-fixed": "#dbe2f8",
        "on-background": "#1a1c1c",
        "on-secondary-fixed-variant": "#404758",
        "primary-container": "#DC0016",
        "surface-container": "#eeeeee",
        "surface-container-low": "#f3f3f3",
        "on-secondary-fixed": "#141b2b",
        "on-surface-variant": "#5c403c",
        "on-tertiary-fixed-variant": "#004494",
        "inverse-on-surface": "#f1f1f1",
        "on-secondary": "#ffffff",
        "outline-sep": "#e6bdb8"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "gutter": "24px",
        "base": "8px",
        "stack-sm": "8px",
        "stack-lg": "32px",
        "stack-md": "16px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        "margin-desktop": "48px"
      },
      "fontFamily": {
        "headline-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-xl": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }]
      }
    }
  },
  plugins: [],
}
